const ACTIONS = {
  LOGIN: "LOGIN",
  GET_TOKEN: "GET_TOKEN",
  GET_USER: "GET_USER",
  GET_ALL_USER: "GET_ALL_USER",
  GET_USER_WALLET: "GET_USER_WALLET",
  GET_TRANSACTION: "GET_TRANSACTION",
  GET_ALL_TRANSACTION: "GET_ALL_TRANSACTION",
};

export default ACTIONS;
